[package]
name = "dymex"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "3.0"
thiserror = "2.0.12"
itertools = "*"

[dev-dependencies]
assert_matches = "1.5"

[features]
default = []
single_precision = []
